[tool.poetry]
name = "mcnp_project"
version = "0.1.0"
description = ""
authors = ["Angus Hollands <goosey15@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
colorama = "^0.3.9"
PILLOW = "^5.1"
selenium = "^3.11"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
